@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container(lighting, "Сервис освещения", "Go")

Boundary(lighting_internals, "Внутренности") {
    Component(api, "REST API", "Gin", "Приём команд")
    Component(logic, "Логика освещения", "Go", "Вкл/Выкл, яркость")
    Component(device_adapter, "Адаптер света", "MQTT", "Команды лампочкам")
    Component(event_publisher, "Публикатор событий", "AMQP", "События изменения освещения")
    Component(repo, "Репозиторий", "GORM", "Работа с БД")
}

ContainerDb(lighting_db, "БД освещения", "PostgreSQL")
Container(message_broker, "Брокер сообщений", "RabbitMQ")
System_Ext(partner_devices, "Устройства партнёров")
Container(api_gateway, "API Gateway")

Rel(api_gateway, api, "REST")
Rel(api, logic, "вызывает")
Rel(logic, repo, "использует")
Rel(logic, device_adapter, "отправляет")
Rel(logic, event_publisher, "публикует")
Rel(device_adapter, partner_devices, "MQTT")
Rel(event_publisher, message_broker, "AMQP")
Rel(repo, lighting_db, "SQL")

@enduml