@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container(telemetry, "Сервис телеметрии", "Go")

Boundary(telemetry_internals, "Внутренности Сервиса телеметрии") {
    Component(ingest_api, "Ingress API", "REST / MQTT", "Принимает показания от датчиков")
    Component(validator, "Валидатор", "Go", "Проверяет корректность данных (диапазоны, метки)")
    Component(processor, "Процессор", "Go", "Агрегирует, сглаживает, преобразует")
    Component(writer, "Писатель в БД", "TimescaleDB client", "Сохраняет во временной ряд")
    Component(event_publisher, "Публикатор событий", "AMQP", "Отправляет события о новых показаниях")
}

ContainerDb(telemetry_db, "БД телеметрии", "TimescaleDB")
System_Ext(partner_devices, "Устройства партнёров", "MQTT")
Container(message_broker, "Брокер сообщений", "RabbitMQ / Kafka")

Rel(partner_devices, ingest_api, "MQTT / HTTP", "Показания")
Rel(api_gateway, ingest_api, "REST", "Получение телеметрии по запросу")
Rel(ingest_api, validator, "вызывает")
Rel(validator, processor, "вызывает")
Rel(processor, writer, "вызывает")
Rel(processor, event_publisher, "вызывает")
Rel(writer, telemetry_db, "SQL")
Rel(event_publisher, message_broker, "AMQP")

@enduml